    FROM node:20-alpine AS builder
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install
    
    COPY . .
    
    ENV NODE_ENV=production
    ENV PORT=8080

    RUN npm run build
    
    
    FROM gcr.io/distroless/nodejs20-debian11
    WORKDIR /app
    ENV NODE_ENV=production
    
    COPY --from=builder /app/.next/standalone ./
    COPY --from=builder /app/.next/static ./.next/static
    
  EXPOSE 8080
  
    CMD ["server.js"]
    